#!/usr/bin/env bash
# Full verification pass: kernel build → disk images → structural verify →
# QEMU boot tests (SeaBIOS + OVMF). Skips QEMU cases cleanly when absent.
# A skipped external check is counted in the final verdict, never treated as a pass.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FAILED=0
mkdir -p "$ROOT/build"
ORACLE_OUT="$ROOT/build/check-stage7-oracle.log"
BOOTTEST_OUT="$ROOT/build/check-stage8-boottest.log"
RTC_OUT="$ROOT/build/check-stage10-rtc.log"
CAP_OUT="$ROOT/build/check-stage11-cap.log"
SKIPPED_RTC=0
SKIPPED_CAP=0
SKIPPED_SHELL=0
SKIPPED_ELF64=0

PYCMD=()
if command -v py >/dev/null 2>&1; then PYCMD=(py -3)
elif command -v python3 >/dev/null 2>&1; then PYCMD=(python3)
elif command -v python >/dev/null 2>&1; then PYCMD=(python)
elif [ -f "/c/Windows/py.exe" ]; then PYCMD=(/c/Windows/py.exe -3)
fi
[ ${#PYCMD[@]} -gt 0 ] || { echo "check: no usable python launcher found" >&2; exit 1; }

echo "=== check 1/13: boot-chain trust"
bash "$ROOT/scripts/trust.sh" verify || FAILED=1

echo
echo "=== check 2/13: kernel build (SAC-retry wrapper, see docs/sac-build-blocks.md)"
# Windows Smart App Control intermittently blocks rust-lld ("os error
# 4551"); scripts/cargo-retry.sh retries exactly that signature and
# passes every other failure through unchanged with its original code
# (harness: scripts/test-cargo-retry.sh). On Linux/CI the signature never
# matches, so the wrapper is a transparent passthrough there.
if [ -d "$HOME/.cargo/bin" ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi
(
  cd "$ROOT/kernel" &&
  if command -v cargo >/dev/null 2>&1; then bash "$ROOT/scripts/cargo-retry.sh" build --release
  else echo "check: cargo not found (install rustup)" >&2; exit 1
  fi
) || FAILED=1

echo
echo "=== check 3/13: disk images"
export PATH="$HOME/.cargo/bin:$PATH"
bash "$ROOT/scripts/build-disk.sh" release || FAILED=1
NOVA_TEST=1 bash "$ROOT/scripts/build-disk.sh" release >/dev/null || FAILED=1

echo
echo "=== check 4/13: host tests"
"${PYCMD[@]}" "$ROOT/tests/test_font_ref.py" || FAILED=1
"${PYCMD[@]}" "$ROOT/tests/test_trust.py" || FAILED=1
"${PYCMD[@]}" "$ROOT/tests/test_schema_drift.py" || FAILED=1

echo
echo "=== check 5/13: structural verification (regular image)"
"${PYCMD[@]}" "$ROOT/tools/verify-disk.py" \
  "$ROOT/build/nova.hdd" \
  "$ROOT/kernel" \
  "$ROOT/.freebuff/ref/limine/limine-binary" \
  "$ROOT/kernel/target/x86_64-unknown-none/release/nucleus" || FAILED=1

echo
echo "=== check 6/13: fuzz the verifier (${FUZZ_ITERS:-10000} mutations)"
"${PYCMD[@]}" "$ROOT/tools/fuzz-disk.py" "${FUZZ_ITERS:-10000}" \
  --image "$ROOT/build/nova.hdd" \
  --kernel-dir "$ROOT/kernel" \
  --limine-bin "$ROOT/.freebuff/ref/limine/limine-binary" \
  --kernel-elf "$ROOT/kernel/target/x86_64-unknown-none/release/nucleus" || FAILED=1

echo
echo "=== check 7/13: external oracles (sgdisk / fsck.fat / mdir)"
"${PYCMD[@]}" "$ROOT/tools/oracle-disk.py" \
  "$ROOT/build/nova.hdd" \
  "$ROOT/kernel" \
  "$ROOT/.freebuff/ref/limine/limine-binary" \
  "$ROOT/kernel/target/x86_64-unknown-none/release/nucleus" 2>&1 | tee "$ORACLE_OUT" || FAILED=1

echo
echo "=== check 8/13: QEMU boot tests (SeaBIOS + OVMF)"
bash "$ROOT/kernel/scripts/test-boot.sh" 2>&1 | tee "$BOOTTEST_OUT" || FAILED=1

echo
echo "=== check 9/13: FAT32 external oracles (fsck.fat / mdir on the corpus)"
# The corpus image is generated by tools/gen-fat32-corpus.py and committed.
# fsck.fat validates the filesystem; mdir's listing is diffed byte-for-byte
# against the kernel's FATLIST serial output (docs/logs/k3c-fat-selftest.log
# format) after regenerating the corpus to prove the committed image is
# exactly what the committed generator produces.
CORPUS="$ROOT/kernel/src/fat32_corpus.img"
KLOG="$ROOT/docs/logs/k3c-fat-selftest.log"
if [ ! -f "$CORPUS" ]; then
  echo "SKIP: fat32 corpus image missing ($CORPUS) - run tools/gen-fat32-corpus.py"
  FAILED=1
else
  # Determinism: regenerate to a temp dir and byte-compare.
  "${PYCMD[@]}" "$ROOT/tools/gen-fat32-corpus.py" "$ROOT/build/fat32-regen" \
    >/dev/null || FAILED=1
  if ! cmp -s "$CORPUS" "$ROOT/build/fat32-regen/fat32-corpus.img"; then
    echo "FAIL: fat32 corpus is NOT byte-identical to a fresh regeneration"
    FAILED=1
  else
    echo "fat32 corpus determinism: byte-identical to regeneration"
  fi
  rm -rf "$ROOT/build/fat32-regen"

  if command -v fsck.fat >/dev/null 2>&1; then
    fsck.fat -n -v "$CORPUS" || FAILED=1
  else
    echo "SKIP: fsck.fat not installed (install: apt-get install dosfstools)"
  fi

  if command -v mdir >/dev/null 2>&1; then
    MDIR_OUT="$ROOT/build/check-stage9-mdir.log"
    # Non-concise default listing of the three listed directories. mdir
    # prints a volume-label header line and per-directory headers; the
    # diff below therefore compares FILE LINES + SUMMARY lines only,
    # extracting the same lines the kernel's FATLIST blocks contain.
    : > "$MDIR_OUT"
    for D in "::/" "::/projects" "::/projects/2026 january notes"; do
      echo "FATLIST $D" >> "$MDIR_OUT"
      mdir -i "$CORPUS" "$D" 2>&1 | grep -E "^( [A-Z0-9~]| [a-z]|  *[0-9]+ file)" >> "$MDIR_OUT"
    done
    echo "FATLIST END" >> "$MDIR_OUT"
    # The kernel's serial capture is the reference for the file lines.
    "${PYCMD[@]}" - "$KLOG" "$MDIR_OUT" <<'PYEOF' || FAILED=1
import sys
kpath, mpath = sys.argv[1], sys.argv[2]

def blocks(path):
    out, cur = {}, None
    for line in open(path, encoding='utf-8', errors='replace').read().splitlines():
        line = line.rstrip('\r')
        if line.startswith('FATLIST ') and line != 'FATLIST END':
            cur = line[8:].strip()
            out[cur] = []
        elif line == 'FATLIST END':
            cur = None
        elif cur is not None and line.strip():
            out[cur].append(line)
    return out

k = blocks(kpath)
m = blocks(mpath)
# mdir headers label the directories differently (drive prefix, :://);
# normalize by order: the kernel lists /, /projects, /projects/2026...
keys_k = list(k.keys())
keys_m = list(m.keys())
ok = True
for i, kk in enumerate(keys_k):
    km = keys_m[i] if i < len(keys_m) else None
    if km is None or k[kk] != m[km]:
        ok = False
        print(f'  MISMATCH kernel {kk!r} vs mdir {km!r}:')
        for a, b in zip(k[kk], (m.get(km) or [])):
            if a != b:
                print(f'    kernel: {a!r}')
                print(f'    mdir  : {b!r}')
        if len(k[kk]) != len(m.get(km) or []):
            print(f'    line counts: kernel {len(k[kk])} vs mdir {len(m.get(km) or [])}')
print('mdir-vs-kernel:', 'IDENTICAL' if ok else 'DIFFER')
sys.exit(0 if ok else 1)
PYEOF
  else
    echo "SKIP: mdir not installed (install: apt-get install mtools) - the"
    echo "      local mdir-vs-kernel diff cannot run here; CI covers it"
  fi
fi

echo
echo "=== check 10/13: CMOS RTC bracket oracle (guest clock vs host UTC)"
# The rtc gate inside the selftest image prints RTC_READ evidence lines;
# this harness brackets the guest epoch between two host-UTC samples
# (QEMU seeds the guest RTC via -rtc base=utc). Exit 2 = harness could not
# run (no QEMU/python/image); that is counted as a skip, not a pass.
bash "$ROOT/kernel/scripts/test-rtc.sh" 2>&1 | tee "$RTC_OUT"
RTC_RC=${PIPESTATUS[0]}
if [ "$RTC_RC" -eq 0 ]; then
  :
elif [ "$RTC_RC" -eq 2 ]; then
  echo "note: RTC bracket oracle skipped (harness could not run) - not a pass"
  SKIPPED_RTC=1
else
  FAILED=1
fi

echo
echo "=== check 11/13: kernel capability oracle (K4: vocabulary + denial probes)"
# The K4 host oracle: signs the kernel's claimed vocabulary into a REAL C2
# manifest and verifies it (with fail-closed negatives), then reboots the
# selftest image and recomputes every CAP_KERNEL_PROBE line from its own
# parse of cap.rs. Exit 2 = harness could not run; counted as a skip.
bash "$ROOT/kernel/scripts/test-cap.sh" 2>&1 | tee "$CAP_OUT"
CAP_RC=${PIPESTATUS[0]}
if [ "$CAP_RC" -eq 0 ]; then
  :
elif [ "$CAP_RC" -eq 2 ]; then
  echo "note: cap oracle skipped (harness could not run) - not a pass"
  SKIPPED_CAP=1
else
  FAILED=1
fi

echo
echo "=== check 12/13: interactive shell oracle (sendkey-driven, prompt-echo waits)"
# The K2/K3 shell driven from a script: the driver types every dispatch()
# verb over the monitor's sendkey path into the REGULAR image, awaits each
# keystroke by its console echo and each command by the next `nova> `
# prompt (no fixed sleeps), and checks every reply against oracles outside
# the binary: a host-grep of shell.rs (verb list), the committed transcript
# format (help/ver/mem replies), a `zz` unknown-command control, and the
# host UTC clock bracketing the guest's `time` stamp. Exit 2 = harness
# could not run; counted as a skip, never a pass.
SHELL_OUT="$ROOT/build/check-stage12-shell.log"
bash "$ROOT/kernel/scripts/test-shell.sh" 2>&1 | tee "$SHELL_OUT"
SHELL_RC=${PIPESTATUS[0]}
if [ "$SHELL_RC" -eq 0 ]; then
  :
elif [ "$SHELL_RC" -eq 2 ]; then
  echo "note: shell oracle skipped (harness could not run) - not a pass"
  SKIPPED_SHELL=1
else
  FAILED=1
fi

echo
echo "=== check 13/13: ELF64 loader oracle (K4b: fixture determinism + spec oracle + guest gate)"
# The supervisor-side ELF64 loader driven end to end: committed fixtures
# re-generated and byte-diffed (determinism), tools/verify-elf64.py (the
# gABI-derived host oracle) accepting the positive and rejecting all ten
# negatives, the live oracle digest diffed against the gate's committed
# STAGED_SHA256 constant, and the selftest image booted with every
# ELF_KERNEL_PROBE line re-derived from the documented staging rule and
# the guest's own sha256 digest equated to the host oracle's. Exit 2 =
# harness could not run; counted as a skip, never a pass.
ELF64_OUT="$ROOT/build/check-stage13-elf64.log"
bash "$ROOT/kernel/scripts/test-elf64.sh" 2>&1 | tee "$ELF64_OUT"
ELF64_RC=${PIPESTATUS[0]}
if [ "$ELF64_RC" -eq 0 ]; then
  :
elif [ "$ELF64_RC" -eq 2 ]; then
  echo "note: elf64 oracle skipped (harness could not run) - not a pass"
  SKIPPED_ELF64=1
else
  FAILED=1
fi

echo
if [ "$FAILED" -ne 0 ]; then
  echo "check: FAILURES (see above)"
  exit 1
fi

# A skipped check is not a pass: count the SKIP lines the stages emitted
# (oracles without their tools, boot tests without QEMU or firmware) and
# say so in the verdict instead of claiming ALL PASSED.
SKIPPED=$(grep -hE '^[[:space:]]*SKIP |UEFI case skipped' "$ORACLE_OUT" "$BOOTTEST_OUT" "$RTC_OUT" "$CAP_OUT" "$SHELL_OUT" "$ELF64_OUT" 2>/dev/null | wc -l)
if [ "$SKIPPED_RTC" -ne 0 ]; then
  SKIPPED=$((SKIPPED + 1))
fi
if [ "$SKIPPED_CAP" -ne 0 ]; then
  SKIPPED=$((SKIPPED + 1))
fi
if [ "$SKIPPED_SHELL" -ne 0 ]; then
  SKIPPED=$((SKIPPED + 1))
fi
if [ "$SKIPPED_ELF64" -ne 0 ]; then
  SKIPPED=$((SKIPPED + 1))
fi
if [ "$SKIPPED" -gt 0 ]; then
  echo "check: PASSED WITH $SKIPPED SKIPPED (skips are not passes - install the missing tools for full coverage)"
  exit 0
fi
echo "check: ALL PASSED"
exit 0
