#!/usr/bin/env bash
# Full verification pass: kernel build → disk images → structural verify →
# QEMU boot tests (SeaBIOS + OVMF). Skips QEMU cases cleanly when absent.
# A skipped external check is counted in the final verdict, never treated as a pass.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FAILED=0
mkdir -p "$ROOT/build"
ORACLE_OUT="$ROOT/build/check-stage7-oracle.log"
BOOTTEST_OUT="$ROOT/build/check-stage8-boottest.log"
RTC_OUT="$ROOT/build/check-stage10-rtc.log"
CAP_OUT="$ROOT/build/check-stage11-cap.log"
SKIPPED_RTC=0
SKIPPED_CAP=0
SKIPPED_SHELL=0
SKIPPED_ELF64=0
SKIPPED_C3=0
SKIPPED_FAT=0

PYCMD=()
if command -v py >/dev/null 2>&1; then PYCMD=(py -3)
elif command -v python3 >/dev/null 2>&1; then PYCMD=(python3)
elif command -v python >/dev/null 2>&1; then PYCMD=(python)
elif [ -f "/c/Windows/py.exe" ]; then PYCMD=(/c/Windows/py.exe -3)
fi
[ ${#PYCMD[@]} -gt 0 ] || { echo "check: no usable python launcher found" >&2; exit 1; }

echo "=== check 1/14: boot-chain trust"
bash "$ROOT/scripts/trust.sh" verify || FAILED=1

echo
echo "=== check 2/14: kernel build (SAC-retry wrapper, see docs/sac-build-blocks.md)"
# Windows Smart App Control intermittently blocks rust-lld ("os error
# 4551"); scripts/cargo-retry.sh retries exactly that signature and
# passes every other failure through unchanged with its original code
# (harness: scripts/test-cargo-retry.sh). On Linux/CI the signature never
# matches, so the wrapper is a transparent passthrough there.
if [ -d "$HOME/.cargo/bin" ]; then
  export PATH="$HOME/.cargo/bin:$PATH"
fi
(
  cd "$ROOT/kernel" &&
  if command -v cargo >/dev/null 2>&1; then bash "$ROOT/scripts/cargo-retry.sh" build --release
  else echo "check: cargo not found (install rustup)" >&2; exit 1
  fi
) || FAILED=1

echo
echo "=== check 3/14: disk images"
export PATH="$HOME/.cargo/bin:$PATH"
bash "$ROOT/scripts/build-disk.sh" release || FAILED=1
NOVA_TEST=1 bash "$ROOT/scripts/build-disk.sh" release >/dev/null || FAILED=1

echo
echo "=== check 4/14: host tests"
"${PYCMD[@]}" "$ROOT/tests/test_font_ref.py" || FAILED=1
"${PYCMD[@]}" "$ROOT/tests/test_trust.py" || FAILED=1
"${PYCMD[@]}" "$ROOT/tests/test_schema_drift.py" || FAILED=1
"${PYCMD[@]}" "$ROOT/tests/test_atomic_install.py" || FAILED=1
"${PYCMD[@]}" "$ROOT/tests/test_bios_install.py" || FAILED=1

echo
echo "=== check 5/14: structural verification (regular image)"
"${PYCMD[@]}" "$ROOT/tools/verify-disk.py" \
  "$ROOT/build/nova.hdd" \
  "$ROOT/kernel" \
  "$ROOT/.freebuff/ref/limine/limine-binary" \
  "$ROOT/kernel/target/x86_64-unknown-none/release/nucleus" || FAILED=1

echo
echo "=== check 6/14: fuzz the verifier (${FUZZ_ITERS:-10000} mutations)"
"${PYCMD[@]}" "$ROOT/tools/fuzz-disk.py" "${FUZZ_ITERS:-10000}" \
  --image "$ROOT/build/nova.hdd" \
  --kernel-dir "$ROOT/kernel" \
  --limine-bin "$ROOT/.freebuff/ref/limine/limine-binary" \
  --kernel-elf "$ROOT/kernel/target/x86_64-unknown-none/release/nucleus" || FAILED=1

echo
echo "=== check 7/14: external oracles (sgdisk / fsck.fat / mdir)"
"${PYCMD[@]}" "$ROOT/tools/oracle-disk.py" \
  "$ROOT/build/nova.hdd" \
  "$ROOT/kernel" \
  "$ROOT/.freebuff/ref/limine/limine-binary" \
  "$ROOT/kernel/target/x86_64-unknown-none/release/nucleus" 2>&1 | tee "$ORACLE_OUT" || FAILED=1

echo
echo "=== check 8/14: QEMU boot tests (SeaBIOS + OVMF)"
bash "$ROOT/kernel/scripts/test-boot.sh" 2>&1 | tee "$BOOTTEST_OUT" || FAILED=1

echo
echo "=== check 9/14: FAT32 external oracles (fsck.fat / mdir on the corpus)"
# The corpus image is generated by tools/gen-fat32-corpus.py and committed.
# fsck.fat validates the filesystem; mdir's listing is diffed byte-for-byte
# against the FATLIST serial output of THIS run's selftest boot (stage 8
# keeps it), after regenerating the corpus to prove the committed image is
# exactly what the committed generator produces. (Until R2 it diffed a
# committed log, docs/logs/k3c-fat-selftest.log, which a renderer change
# would never have updated.)
CORPUS="$ROOT/kernel/src/fat32_corpus.img"
KLOG="$ROOT/build/serial-SeaBIOS-selftest.log"
if [ ! -f "$CORPUS" ]; then
  echo "SKIP: fat32 corpus image missing ($CORPUS) - run tools/gen-fat32-corpus.py"
  FAILED=1
else
  # Determinism: regenerate to a temp dir and byte-compare.
  "${PYCMD[@]}" "$ROOT/tools/gen-fat32-corpus.py" "$ROOT/build/fat32-regen" \
    >/dev/null || FAILED=1
  if ! cmp -s "$CORPUS" "$ROOT/build/fat32-regen/fat32-corpus.img"; then
    echo "FAIL: fat32 corpus is NOT byte-identical to a fresh regeneration"
    FAILED=1
  else
    echo "fat32 corpus determinism: byte-identical to regeneration"
  fi
  rm -rf "$ROOT/build/fat32-regen"

  # Spec rules (FAT type by cluster count, FAT size) on every host, so a
  # non-FAT32 corpus fails here too, not only where fsck.fat/mdir exist.
  "${PYCMD[@]}" "$ROOT/tools/verify-fat32.py" "$CORPUS" || FAILED=1

  if command -v fsck.fat >/dev/null 2>&1; then
    # Exit code printed: R2's done-criterion is "fsck.fat exits 0", and
    # the log must show it, not imply it.
    fsck.fat -n -v "$CORPUS"; FSCK_RC=$?
    echo "fsck.fat exit $FSCK_RC"
    [ "$FSCK_RC" -eq 0 ] || FAILED=1
  else
    echo "SKIP: fsck.fat not installed (install: apt-get install dosfstools)"
    SKIPPED_FAT=$((SKIPPED_FAT + 1))
  fi

  if command -v mdir >/dev/null 2>&1; then
    # mdir_vs_kernel IMAGE OUT RAW: list three directories of IMAGE with
    # real mdir (OUT: headers dropped, RAW: verbatim), then diff OUT
    # against this run's kernel FATLIST blocks. Exit 0 = IDENTICAL.
    mdir_vs_kernel() {
    local IMG="$1" MDIR_OUT="$2" MDIR_RAW="$3"
    # Default (non-concise) listing of the three listed directories. Only
    # mdir's own header/footer lines are dropped - the volume lines,
    # "Directory for", "bytes free" and blanks, as seen in real mdir output
    # (docs/logs/ci1-run-36001422533-green-stage7-8.log). Everything else,
    # error text included, reaches the diff. The earlier include-filter
    # required a leading space, which real file lines do not have, and it
    # hid mdir's errors (0 lines, no reason given).
    : > "$MDIR_OUT"
    : > "$MDIR_RAW"
    for D in "::/" "::/projects" "::/projects/2026 january notes"; do
      echo "FATLIST $D" >> "$MDIR_OUT"
      echo "--- mdir -i corpus $D" >> "$MDIR_RAW"
      mdir -i "$IMG" "$D" >> "$MDIR_RAW" 2>&1
      echo "(exit $?)" >> "$MDIR_RAW"
      mdir -i "$IMG" "$D" 2>&1 \
        | grep -vE "^ Volume in drive |^ Volume Serial Number |^Directory for |bytes free$|^[[:space:]]*$" >> "$MDIR_OUT"
    done
    echo "FATLIST END" >> "$MDIR_OUT"
    "${PYCMD[@]}" - "$KLOG" "$MDIR_OUT" <<'PYEOF'
import sys
kpath, mpath = sys.argv[1], sys.argv[2]

def blocks(path):
    out, cur = {}, None
    for line in open(path, encoding='utf-8', errors='replace').read().splitlines():
        line = line.rstrip('\r')
        if line.startswith('FATLIST ') and line != 'FATLIST END':
            cur = line[8:].strip()
            out[cur] = []
        elif line == 'FATLIST END':
            cur = None
        elif cur is not None and line.strip():
            out[cur].append(line)
    return out

k = blocks(kpath)
m = blocks(mpath)
if not k or len(k) != len(m):
    # Zero kernel blocks would make the loop below vacuous ("IDENTICAL").
    print(f'  FATLIST block count: kernel {len(k)} vs mdir {len(m)}')
    print('mdir-vs-kernel: DIFFER')
    sys.exit(1)
# mdir headers label the directories differently (drive prefix, :://);
# normalize by order: the kernel lists /, /projects, /projects/2026...
keys_k = list(k.keys())
keys_m = list(m.keys())
ok = True
for i, kk in enumerate(keys_k):
    km = keys_m[i] if i < len(keys_m) else None
    if km is None or k[kk] != m[km]:
        ok = False
        print(f'  MISMATCH kernel {kk!r} vs mdir {km!r}:')
        for a, b in zip(k[kk], (m.get(km) or [])):
            if a != b:
                print(f'    kernel: {a!r}')
                print(f'    mdir  : {b!r}')
        if len(k[kk]) != len(m.get(km) or []):
            print(f'    line counts: kernel {len(k[kk])} vs mdir {len(m.get(km) or [])}')
print('mdir-vs-kernel:', 'IDENTICAL' if ok else 'DIFFER')
sys.exit(0 if ok else 1)
PYEOF
    }
    MDIR_RAW="$ROOT/build/check-stage9-mdir-raw.log"
    mdir_vs_kernel "$CORPUS" "$ROOT/build/check-stage9-mdir.log" "$MDIR_RAW" \
      || { FAILED=1; echo "--- raw mdir output:"; cat "$MDIR_RAW"; }

    # Sabotage gate (R2 break test, every run): one short-name byte changed
    # in a copy of the corpus, kernel serial unchanged. The same diff must
    # say DIFFER, and mdir must show the renamed file (so the DIFFER is the
    # rename, not an mdir error). An IDENTICAL here means the diff is
    # decorative.
    MUT="$ROOT/build/fat32-mutant.img"
    MUT_OUT="$ROOT/build/check-stage9-mdir-mutant.log"
    echo "--- sabotage gate: SIMPLE.TXT renamed RIMPLE.TXT in a corpus copy"
    if "${PYCMD[@]}" -c 'import sys; d = bytearray(open(sys.argv[1], "rb").read()); i = d.find(b"SIMPLE  TXT"); assert i > 0; d[i] ^= 0x01; open(sys.argv[2], "wb").write(d)' "$CORPUS" "$MUT"; then
      if mdir_vs_kernel "$MUT" "$MUT_OUT" "$ROOT/build/check-stage9-mdir-mutant-raw.log"; then
        echo "FAIL: sabotage gate: the renamed corpus still compares IDENTICAL"
        FAILED=1
      elif ! grep -q "^RIMPLE   TXT" "$MUT_OUT"; then
        echo "FAIL: sabotage gate: mdir did not list RIMPLE.TXT (DIFFER for another reason)"
        FAILED=1
      else
        echo "SABOTAGE GATE PASS: renamed corpus compares DIFFER"
      fi
    else
      echo "FAIL: sabotage gate: could not build the renamed corpus copy"
      FAILED=1
    fi
    rm -f "$MUT"
  else
    SKIPPED_FAT=$((SKIPPED_FAT + 1))
    echo "SKIP: mdir not installed (install: apt-get install mtools) - the"
    echo "      local mdir-vs-kernel diff cannot run here; CI covers it"
  fi
fi

echo
echo "=== check 10/14: CMOS RTC bracket oracle (guest clock vs host UTC)"
# The rtc gate inside the selftest image prints RTC_READ evidence lines;
# this harness brackets the guest epoch between two host-UTC samples
# (QEMU seeds the guest RTC via -rtc base=utc). Exit 2 = harness could not
# run (no QEMU/python/image); that is counted as a skip, not a pass.
bash "$ROOT/kernel/scripts/test-rtc.sh" 2>&1 | tee "$RTC_OUT"
RTC_RC=${PIPESTATUS[0]}
if [ "$RTC_RC" -eq 0 ]; then
  :
elif [ "$RTC_RC" -eq 2 ]; then
  echo "note: RTC bracket oracle skipped (harness could not run) - not a pass"
  SKIPPED_RTC=1
else
  FAILED=1
fi

echo
echo "=== check 11/14: kernel capability oracle (K4: vocabulary + denial probes)"
# The K4 host oracle: signs the kernel's claimed vocabulary into a REAL C2
# manifest and verifies it (with fail-closed negatives), then reboots the
# selftest image and recomputes every CAP_KERNEL_PROBE line from its own
# parse of cap.rs. Exit 2 = harness could not run; counted as a skip.
bash "$ROOT/kernel/scripts/test-cap.sh" 2>&1 | tee "$CAP_OUT"
CAP_RC=${PIPESTATUS[0]}
if [ "$CAP_RC" -eq 0 ]; then
  :
elif [ "$CAP_RC" -eq 2 ]; then
  echo "note: cap oracle skipped (harness could not run) - not a pass"
  SKIPPED_CAP=1
else
  FAILED=1
fi

echo
echo "=== check 12/14: interactive shell oracle (sendkey-driven, prompt-echo waits)"
# The K2/K3 shell driven from a script: the driver types every dispatch()
# verb over the monitor's sendkey path into the REGULAR image, awaits each
# keystroke by its console echo and each command by the next `nova> `
# prompt (no fixed sleeps), and checks every reply against oracles outside
# the binary: a host-grep of shell.rs (verb list), the committed transcript
# format (help/ver/mem replies), a `zz` unknown-command control, and the
# host UTC clock bracketing the guest's `time` stamp. Exit 2 = harness
# could not run; counted as a skip, never a pass.
SHELL_OUT="$ROOT/build/check-stage12-shell.log"
bash "$ROOT/kernel/scripts/test-shell.sh" 2>&1 | tee "$SHELL_OUT"
SHELL_RC=${PIPESTATUS[0]}
if [ "$SHELL_RC" -eq 0 ]; then
  :
elif [ "$SHELL_RC" -eq 2 ]; then
  echo "note: shell oracle skipped (harness could not run) - not a pass"
  SKIPPED_SHELL=1
else
  FAILED=1
fi

echo
echo "=== check 13/14: ELF64 loader oracle (K4b: fixture determinism + spec oracle + guest gate)"
# The supervisor-side ELF64 loader driven end to end: committed fixtures
# re-generated and byte-diffed (determinism), tools/verify-elf64.py (the
# gABI-derived host oracle) accepting the positive and rejecting all ten
# negatives, the live oracle digest diffed against the gate's committed
# STAGED_SHA256 constant, and the selftest image booted with every
# ELF_KERNEL_PROBE line re-derived from the documented staging rule and
# the guest's own sha256 digest equated to the host oracle's. Exit 2 =
# harness could not run; counted as a skip, never a pass.
ELF64_OUT="$ROOT/build/check-stage13-elf64.log"
bash "$ROOT/kernel/scripts/test-elf64.sh" 2>&1 | tee "$ELF64_OUT"
ELF64_RC=${PIPESTATUS[0]}
if [ "$ELF64_RC" -eq 0 ]; then
  :
elif [ "$ELF64_RC" -eq 2 ]; then
  echo "note: elf64 oracle skipped (harness could not run) - not a pass"
  SKIPPED_ELF64=1
else
  FAILED=1
fi

echo
echo "=== check 14/14: C3 atomic-install boot oracle (A/B slots, fault-point sweep, rollback)"
# The C3 gate: a failed or interrupted install always leaves a bootable
# machine. Every interruption state the installer can produce (one per
# logical operation, plus mid-content kills, plus the between-commits
# crash) is BOOTED under SeaBIOS; the between-commits state is booted on
# both firmwares; a mutant that commits an unwritten chain must NOT boot.
# Exit 2 = harness could not run; counted as a skip, never a pass.
C3_OUT="$ROOT/build/check-stage14-c3.log"
bash "$ROOT/scripts/test-atomic-install.sh" 2>&1 | tee "$C3_OUT"
C3_RC=${PIPESTATUS[0]}
if [ "$C3_RC" -eq 0 ]; then
  # rc 0 can still carry internal skips (no UEFI firmware for the OVMF
  # boots): CI run 37935532518 skipped both and still exited 0.
  SKIPPED_C3=$(grep -c '^[[:space:]]*SKIP:' "$C3_OUT")
elif [ "$C3_RC" -eq 2 ]; then
  echo "note: c3 atomic-install oracle skipped (harness could not run) - not a pass"
  SKIPPED_C3=1
else
  FAILED=1
fi

echo
if [ "$FAILED" -ne 0 ]; then
  echo "check: FAILURES (see above)"
  exit 1
fi

# A skipped check is not a pass: count the SKIP lines the stages emitted
# (oracles without their tools, boot tests without QEMU or firmware) and
# say so in the verdict instead of claiming ALL PASSED.
SKIPPED=$(grep -hE '^[[:space:]]*SKIP |UEFI case skipped' "$ORACLE_OUT" "$BOOTTEST_OUT" "$RTC_OUT" "$CAP_OUT" "$SHELL_OUT" "$ELF64_OUT" 2>/dev/null | wc -l)
if [ "$SKIPPED_RTC" -ne 0 ]; then
  SKIPPED=$((SKIPPED + 1))
fi
if [ "$SKIPPED_CAP" -ne 0 ]; then
  SKIPPED=$((SKIPPED + 1))
fi
if [ "$SKIPPED_SHELL" -ne 0 ]; then
  SKIPPED=$((SKIPPED + 1))
fi
if [ "$SKIPPED_ELF64" -ne 0 ]; then
  SKIPPED=$((SKIPPED + 1))
fi
SKIPPED=$((SKIPPED + SKIPPED_FAT + SKIPPED_C3))
# test-boot.sh exits 0 after "SKIP: ..." (no QEMU, no images); the pattern
# above needs "SKIP " with a space, so count those lines here.
BOOT_SKIPS=$(grep -c '^SKIP: ' "$BOOTTEST_OUT" 2>/dev/null)
SKIPPED=$((SKIPPED + ${BOOT_SKIPS:-0}))
# CI installs every tool, so a skip there means an oracle silently did not
# run (stages 11-13 skipped for weeks behind a PATH-lookup bug while the
# verdict stayed exit 0). GitHub Actions sets CI=true.
if [ "$SKIPPED" -gt 0 ] && [ "${CI:-}" = "true" ]; then
  echo "check: FAILED - $SKIPPED SKIPPED in CI (every oracle must run there)"
  exit 1
fi
if [ "$SKIPPED" -gt 0 ]; then
  echo "check: PASSED WITH $SKIPPED SKIPPED (skips are not passes - install the missing tools for full coverage)"
  exit 0
fi
echo "check: ALL PASSED"
exit 0
