#!/usr/bin/env python3
"""Generate kernel/src/font_data.rs from the vendored dhepper/font8x8_basic.h
reference. Writes the full 95-glyph printable-ASCII atlas plus the (char,
rows) reference table used by the kernel's runtime drift check and by
tests/font_ref_test.py."""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REF = REPO / ".freebuff/ref/font8x8_basic.h"
OUT = REPO / "kernel/src/font_data.rs"

FIRST, LAST = 0x20, 0x7E
COUNT = LAST - FIRST + 1


def parse_reference() -> dict[int, list[int]]:
    text = REF.read_text(encoding="utf-8", errors="replace")
    glyphs: dict[int, list[int]] = {}
    # File layout: one 128x8 array, each entry `{ 0x.., ... }` followed by a
    # `// U+XXXX (name)` comment.
    for m in re.finditer(
        r"\{\s*(0x[0-9A-Fa-f]{2}(?:\s*,\s*0x[0-9A-Fa-f]{2}){7})\s*\}\s*,?\s*//\s*U\+([0-9A-Fa-f]{4})",
        text,
    ):
        rows = [int(x, 16) for x in m.group(1).split(",")]
        glyphs[int(m.group(2), 16)] = rows
    return glyphs


def rust_escape(ch: int) -> str:
    if ch == 0x5C:  # backslash
        return "\\\\"
    if ch == 0x27:  # quote
        return "\\'"
    return chr(ch)


def main() -> int:
    if not REF.exists():
        print(f"gen-font: reference missing: {REF}")
        return 1
    glyphs = parse_reference()
    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        print(f"gen-font: reference missing glyphs: {[hex(c) for c in missing]}")
        return 1

    lines: list[str] = []
    lines.append("//! GENERATED by tools/gen-font.py from .freebuff/ref/font8x8_basic.h — do not edit.\n")
    lines.append(f"//! dhepper/font8x8 (public domain); {COUNT} glyphs, 0x20..=0x7E, LSB=left.\n")
    lines.append(f"pub const FIRST_CHAR: u8 = 0x{FIRST:02X};\n")
    lines.append(f"pub const LAST_CHAR: u8 = 0x{LAST:02X};\n")
    lines.append(f"pub const GLYPH_COUNT: usize = {COUNT};\n\n")
    lines.append(f"pub const GLYPHS: [u8; GLYPH_COUNT * 8] = [\n")
    for c in range(FIRST, LAST + 1):
        rows = glyphs[c]
        lines.append(f"    // {rust_escape(c)}\n")
        lines.append("    " + ", ".join(f"0x{r:02X}" for r in rows) + ",\n")
    lines.append("];\n\n")
    lines.append("/// (char, 8 rows) pairs for the runtime drift check.\n")
    lines.append(f"pub const REF_ROWS: [u8; GLYPH_COUNT * 9] = [\n")
    for c in range(FIRST, LAST + 1):
        rows = glyphs[c]
        lines.append("    " + ", ".join(f"0x{r:02X}" for r in ([c] + rows)) + ",\n")
    lines.append("];\n")

    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"gen-font: wrote {OUT} ({COUNT} glyphs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
