//! Embedded 8×8 bitmap font — full printable ASCII (95 glyphs, 0x20..=0x7E).
//!
//! Data lives in `font_data.rs`, GENERATED by `tools/gen-font.py` from the
//! vendored dhepper/font8x8_basic.h reference (public domain). Each byte is
//! one row, LSB = leftmost pixel. Guarded against bit rot twice: a runtime
//! cross-check here and `tests/font_ref_test.py` at build time.

mod font_data;

pub use font_data::{FIRST_CHAR, GLYPH_COUNT, LAST_CHAR};

use core::sync::atomic::{AtomicU8, Ordering};

pub const GLYPH_W: usize = 8;
pub const GLYPH_H: usize = 8;

pub struct FontAtlas {
    pub bytes: [u8; GLYPH_COUNT * GLYPH_H],
}

impl FontAtlas {
    pub const fn embedded() -> FontAtlas {
        FontAtlas {
            bytes: font_data::GLYPHS,
        }
    }

    pub fn glyph(&self, ch: u8) -> Option<&[u8]> {
        if !(FIRST_CHAR..=LAST_CHAR).contains(&ch) {
            return None;
        }
        let idx = (ch - FIRST_CHAR) as usize * GLYPH_H;
        Some(&self.bytes[idx..idx + GLYPH_H])
    }
}

pub static FONT: FontAtlas = FontAtlas::embedded();

// --- runtime reference check -------------------------------------------------

static CHECK_STATE: AtomicU8 = AtomicU8::new(0);

pub const CHECK_PENDING: u8 = 0;
pub const CHECK_OK: u8 = 1;
pub const CHECK_MISMATCH: u8 = 2;

/// Verify every embedded glyph equals its reference rows.
pub fn verify_against_reference() -> bool {
    let mut all_ok = true;
    let mut i = 0;
    while i < font_data::REF_ROWS.len() {
        let (ch, rows) = (font_data::REF_ROWS[i], &font_data::REF_ROWS[i + 1..i + 9]);
        match FONT.glyph(ch) {
            Some(g) if g == rows => {}
            _ => all_ok = false,
        }
        i += 9;
    }
    CHECK_STATE.store(
        if all_ok { CHECK_OK } else { CHECK_MISMATCH },
        Ordering::Relaxed,
    );
    all_ok
}

pub fn check_state() -> u8 {
    CHECK_STATE.load(Ordering::Relaxed)
}
