//! Embedded 8×8 bitmap font — full printable ASCII (95 glyphs, 0x20..=0x7E).
//!
//! Data lives in `font_data.rs`, GENERATED by `tools/gen-font.py` from the
//! vendored dhepper/font8x8_basic.h reference (public domain). Each byte is
//! one row, LSB = leftmost pixel.
//!
//! Verifiability notes:
//! - The host test `tests/test_font_ref.py` is the byte-exact oracle: it parses
//!   the reference header independently and compares every glyph. Run it via
//!   `scripts/check.sh` (stage 4).
//! - The runtime check below deliberately does NOT compare the table against
//!   its own source (that was a tautology and could never fail). Instead it
//!   checks structural invariants of the table as shipped in the binary:
//!   every non-space printable glyph has at least one pixel on, and no two
//!   printable glyphs are identical. Those properties hold for the real
//!   font8x8 printable range (verified against the reference: 95 glyphs,
//!   blanks = {U+0020} only, zero duplicate pairs) and fail loudly on truncation,
//!   bit rot, or a mis-generated table.

mod font_data;

pub use font_data::{FIRST_CHAR, GLYPH_COUNT, LAST_CHAR};

use core::sync::atomic::{AtomicU8, Ordering};

pub const GLYPH_W: usize = 8;
pub const GLYPH_H: usize = 8;

pub struct FontAtlas {
    pub bytes: [u8; GLYPH_COUNT * GLYPH_H],
}

impl FontAtlas {
    pub const fn embedded() -> FontAtlas {
        FontAtlas {
            bytes: font_data::GLYPHS,
        }
    }

    pub fn glyph(&self, ch: u8) -> Option<&[u8]> {
        if !(FIRST_CHAR..=LAST_CHAR).contains(&ch) {
            return None;
        }
        let idx = (ch - FIRST_CHAR) as usize * GLYPH_H;
        Some(&self.bytes[idx..idx + GLYPH_H])
    }
}

pub static FONT: FontAtlas = FontAtlas::embedded();

// --- runtime structural check ------------------------------------------------

static CHECK_STATE: AtomicU8 = AtomicU8::new(0);

pub const CHECK_PENDING: u8 = 0;
pub const CHECK_OK: u8 = 1;
pub const CHECK_MISMATCH: u8 = 2;

/// Check structural invariants of the embedded table (see module docs).
/// Returns the number of problems found; 0 means the table is sane.
pub fn verify_against_reference() -> usize {
    let mut problems = 0usize;

    // Invariant 1: every glyph except the space (FIRST_CHAR) has at least one
    // pixel set. A zeroed row set means truncation or bit rot.
    for g in 0..GLYPH_COUNT {
        let rows = &FONT.bytes[g * GLYPH_H..(g + 1) * GLYPH_H];
        let blank = rows.iter().all(|&b| b == 0);
        if blank && g != 0 {
            problems += 1;
        }
    }

    // Invariant 2: no two printable glyphs may be identical — if they are,
    // one of them is wrong (the real font8x8 printable range has none).
    for a in 0..GLYPH_COUNT {
        let ra = &FONT.bytes[a * GLYPH_H..(a + 1) * GLYPH_H];
        for b in (a + 1)..GLYPH_COUNT {
            let rb = &FONT.bytes[b * GLYPH_H..(b + 1) * GLYPH_H];
            if ra == rb {
                problems += 1;
            }
        }
    }

    CHECK_STATE.store(
        if problems == 0 {
            CHECK_OK
        } else {
            CHECK_MISMATCH
        },
        Ordering::Relaxed,
    );
    problems
}

pub fn check_state() -> u8 {
    CHECK_STATE.load(Ordering::Relaxed)
}
